name: ci-emscripten

on: [pull_request, workflow_dispatch]

jobs:
    ci-emscripten-3_1_45:
        name: emscripten-3_1_45
        runs-on: ubuntu-latest
        container:
            image: ubuntu:22.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        steps:
            -   name: Install Dependencies
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get install -y \
                        cmake \
                        git \
                        ninja-build \
                        nodejs
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            # Must be done after checkout since it requires the directory structure to be in place.
            -   name: Install emsdk
                run: |
                    git clone https://github.com/emscripten-core/emsdk.git
                    cd emsdk
                    ./emsdk install 3.1.45
                    ./emsdk activate 3.1.45
            -   name: Build
                run: |
                    cd emsdk
                    . ./emsdk_env.sh
                    cd ..
                    mkdir Release
                    cd Release
                    emcmake cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        ..
                    cmake --build . --config Release
            -   name: Test
                run: |
                    cd emsdk
                    . ./emsdk_env.sh
                    cd ../Release
                    node --experimental-wasm-threads --experimental-wasm-bulk-memory ./test/libcoro_test.js
